// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7hFJr-evN4ulhR2-Uj74GUXGiHsOVgwk',
    appId: '1:695656688836:web:3dcaec5f457c79d0c36d91',
    messagingSenderId: '695656688836',
    projectId: 'my-todo-app-d215a',
    authDomain: 'my-todo-app-d215a.firebaseapp.com',
    storageBucket: 'my-todo-app-d215a.firebasestorage.app',
    measurementId: 'G-G6P7F7RC9D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZVUZud4w4nAQk6O8XFD02X3WcGr_YN1k',
    appId: '1:695656688836:android:6efad122ff150063c36d91',
    messagingSenderId: '695656688836',
    projectId: 'my-todo-app-d215a',
    storageBucket: 'my-todo-app-d215a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZM4Cw6nmGz8ol6-dTUvgp143l_d6wV9M',
    appId: '1:695656688836:ios:9bad1048664d5a04c36d91',
    messagingSenderId: '695656688836',
    projectId: 'my-todo-app-d215a',
    storageBucket: 'my-todo-app-d215a.firebasestorage.app',
    iosBundleId: 'com.example.mytodoapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZM4Cw6nmGz8ol6-dTUvgp143l_d6wV9M',
    appId: '1:695656688836:ios:9bad1048664d5a04c36d91',
    messagingSenderId: '695656688836',
    projectId: 'my-todo-app-d215a',
    storageBucket: 'my-todo-app-d215a.firebasestorage.app',
    iosBundleId: 'com.example.mytodoapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC7hFJr-evN4ulhR2-Uj74GUXGiHsOVgwk',
    appId: '1:695656688836:web:f8c4d6c64ea1bd9dc36d91',
    messagingSenderId: '695656688836',
    projectId: 'my-todo-app-d215a',
    authDomain: 'my-todo-app-d215a.firebaseapp.com',
    storageBucket: 'my-todo-app-d215a.firebasestorage.app',
    measurementId: 'G-C7L3N19YYM',
  );
}
